-- Create the ShortQuotes table
CREATE TABLE ShortQuotes (
    QuoteID INT IDENTITY(1,1) PRIMARY KEY,
    Quote VARCHAR(255) NOT NULL,
    Author VARCHAR(100) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    IsFamous BIT NOT NULL,
    Year INT NULL
);

-- Insert 50 sample rows
INSERT INTO ShortQuotes (Quote, Author, Category, IsFamous, Year)
VALUES
('The journey of a thousand miles begins with one step.', 'Lao Tzu', 'Inspirational', 1, -500),
('Life is what happens when you’re busy making other plans.', 'John Lennon', 'Philosophical', 1, 1980),
('Be yourself; everyone else is already taken.', 'Oscar Wilde', 'Humorous', 1, 1880),
('In the middle of every difficulty lies opportunity.', 'Albert Einstein', 'Motivational', 1, 1940),
('Do or do not, there is no try.', 'Yoda', 'Inspirational', 1, NULL),
('Happiness depends upon ourselves.', 'Aristotle', 'Philosophical', 1, -300),
('The only limit to our realization of tomorrow is our doubts of today.', 'Franklin D. Roosevelt', 'Motivational', 1, 1933),
('It always seems impossible until it’s done.', 'Nelson Mandela', 'Inspirational', 1, 1993),
('A day without laughter is a day wasted.', 'Charlie Chaplin', 'Humorous', 1, 1920),
('To be, or not to be, that is the question.', 'William Shakespeare', 'Philosophical', 1, 1600),
('Not all those who wander are lost.', 'J.R.R. Tolkien', 'Inspirational', 1, 1954),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'Motivational', 1, 1945),
('I think, therefore I am.', 'René Descartes', 'Philosophical', 1, 1637),
('Do what you can, with what you have, where you are.', 'Theodore Roosevelt', 'Motivational', 1, 1901),
('Be the change that you wish to see in the world.', 'Mahatma Gandhi', 'Inspirational', 1, 1947),
('Time is money.', 'Benjamin Franklin', 'Philosophical', 1, 1748),
('The purpose of life is a life of purpose.', 'Robert Byrne', 'Philosophical', 1, 1970),
('If you tell the truth, you don’t have to remember anything.', 'Mark Twain', 'Humorous', 1, 1894),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'Motivational', 1, 1945),
('Keep your friends close, but your enemies closer.', 'Sun Tzu', 'Philosophical', 1, -500),
('I have no special talents. I am only passionately curious.', 'Albert Einstein', 'Inspirational', 1, 1930),
('Imagination is more important than knowledge.', 'Albert Einstein', 'Philosophical', 1, 1929),
('Fall seven times and stand up eight.', 'Japanese Proverb', 'Motivational', 0, NULL),
('Strive not to be a success, but rather to be of value.', 'Albert Einstein', 'Inspirational', 1, 1934),
('We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Aristotle', 'Philosophical', 1, -300),
('Do what is right, not what is easy nor what is popular.', 'Roy T. Bennett', 'Inspirational', 0, NULL),
('Act as if what you do makes a difference. It does.', 'William James', 'Motivational', 1, 1890),
('Dream big and dare to fail.', 'Norman Vaughan', 'Inspirational', 0, 1960),
('Life isn’t about finding yourself. It’s about creating yourself.', 'George Bernard Shaw', 'Philosophical', 1, 1905),
('An unexamined life is not worth living.', 'Socrates', 'Philosophical', 1, -400),
('Turn your wounds into wisdom.', 'Oprah Winfrey', 'Motivational', 1, 1999),
('It is never too late to be what you might have been.', 'George Eliot', 'Inspirational', 1, 1869),
('Everything you can imagine is real.', 'Pablo Picasso', 'Philosophical', 1, 1937),
('Happiness is not by chance, but by choice.', 'Jim Rohn', 'Motivational', 1, 1980),
('What we think, we become.', 'Buddha', 'Philosophical', 1, -400),
('A goal without a plan is just a wish.', 'Antoine de Saint-Exupéry', 'Motivational', 1, 1943),
('If opportunity doesn’t knock, build a door.', 'Milton Berle', 'Motivational', 1, 1950),
('Kindness is a language which the deaf can hear and the blind can see.', 'Mark Twain', 'Philosophical', 1, 1885),
('Believe you can and you’re halfway there.', 'Theodore Roosevelt', 'Inspirational', 1, 1905),
('A mind is like a parachute. It doesn’t work if it isn’t open.', 'Frank Zappa', 'Humorous', 1, 1970),
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Inspirational', 1, 2005),
('Don’t cry because it’s over, smile because it happened.', 'Dr. Seuss', 'Humorous', 1, 1957),
('It is our choices that show what we truly are, far more than our abilities.', 'J.K. Rowling', 'Inspirational', 1, 1999),
('Knowledge is power.', 'Francis Bacon', 'Philosophical', 1, 1597),
('Do one thing every day that scares you.', 'Eleanor Roosevelt', 'Inspirational', 1, 1930),
('Hardships often prepare ordinary people for an extraordinary destiny.', 'C.S. Lewis', 'Motivational', 1, 1942),
('Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau', 'Motivational', 1, 1854),
('The only thing we have to fear is fear itself.', 'Franklin D. Roosevelt', 'Motivational', 1, 1933),
('The pen is mightier than the sword.', 'Edward Bulwer-Lytton', 'Philosophical', 1, 1839);

-- Verify the inserted data
SELECT * FROM ShortQuotes;
