-- Create the Bands table
CREATE TABLE Bands (
    BandID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Genre VARCHAR(50) NOT NULL,
    FormationYear INT NOT NULL,
    IsActive BIT NOT NULL,
    Country VARCHAR(50) NOT NULL
);

-- Insert 50 sample rows
INSERT INTO Bands (Name, Genre, FormationYear, IsActive, Country)
VALUES
('The Beatles', 'Rock', 1960, 0, 'United Kingdom'),
('Led Zeppelin', 'Rock', 1968, 0, 'United Kingdom'),
('Pink Floyd', 'Progressive Rock', 1965, 0, 'United Kingdom'),
('Queen', 'Rock', 1970, 1, 'United Kingdom'),
('The Rolling Stones', 'Rock', 1962, 1, 'United Kingdom'),
('Metallica', 'Metal', 1981, 1, 'United States'),
('Nirvana', 'Grunge', 1987, 0, 'United States'),
('Radiohead', 'Alternative', 1985, 1, 'United Kingdom'),
('Coldplay', 'Alternative', 1996, 1, 'United Kingdom'),
('The Eagles', 'Rock', 1971, 1, 'United States'),
('Red Hot Chili Peppers', 'Funk Rock', 1983, 1, 'United States'),
('Green Day', 'Punk Rock', 1987, 1, 'United States'),
('Linkin Park', 'Nu Metal', 1996, 0, 'United States'),
('Imagine Dragons', 'Alternative', 2008, 1, 'United States'),
('Foo Fighters', 'Alternative', 1994, 1, 'United States'),
('The Cure', 'Gothic Rock', 1978, 1, 'United Kingdom'),
('The Clash', 'Punk Rock', 1976, 0, 'United Kingdom'),
('Pearl Jam', 'Grunge', 1990, 1, 'United States'),
('Oasis', 'Britpop', 1991, 0, 'United Kingdom'),
('Arctic Monkeys', 'Indie Rock', 2002, 1, 'United Kingdom'),
('U2', 'Rock', 1976, 1, 'Ireland'),
('The Who', 'Rock', 1964, 1, 'United Kingdom'),
('Fleetwood Mac', 'Rock', 1967, 1, 'United Kingdom'),
('AC/DC', 'Hard Rock', 1973, 1, 'Australia'),
('Bon Jovi', 'Rock', 1983, 1, 'United States'),
('Guns N’ Roses', 'Hard Rock', 1985, 1, 'United States'),
('Slipknot', 'Metal', 1995, 1, 'United States'),
('Rammstein', 'Industrial Metal', 1994, 1, 'Germany'),
('The Killers', 'Alternative', 2001, 1, 'United States'),
('Kings of Leon', 'Alternative', 1999, 1, 'United States'),
('Muse', 'Progressive Rock', 1994, 1, 'United Kingdom'),
('The Smashing Pumpkins', 'Alternative', 1988, 1, 'United States'),
('Blink-182', 'Punk Rock', 1992, 1, 'United States'),
('System of a Down', 'Metal', 1994, 1, 'United States'),
('Paramore', 'Pop Punk', 2004, 1, 'United States'),
('Panic! at the Disco', 'Alternative', 2004, 0, 'United States'),
('My Chemical Romance', 'Emo', 2001, 0, 'United States'),
('Twenty One Pilots', 'Alternative', 2009, 1, 'United States'),
('The White Stripes', 'Rock', 1997, 0, 'United States'),
('The Strokes', 'Indie Rock', 1998, 1, 'United States'),
('The Black Keys', 'Rock', 2001, 1, 'United States'),
('Daft Punk', 'Electronic', 1993, 0, 'France'),
('Tame Impala', 'Psychedelic', 2007, 1, 'Australia'),
('Arcade Fire', 'Indie Rock', 2001, 1, 'Canada'),
('Depeche Mode', 'Electronic', 1980, 1, 'United Kingdom'),
('The Arctic Monkeys', 'Indie Rock', 2002, 1, 'United Kingdom'),
('Joy Division', 'Post-Punk', 1976, 0, 'United Kingdom'),
('Aerosmith', 'Hard Rock', 1970, 1, 'United States'),
('The Doors', 'Rock', 1965, 0, 'United States');

-- Verify the inserted data
SELECT * FROM Bands;
